version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-and-push:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: git config user.email "dosemwegie@gmail.com"
            - run: git config user.name "David Osemwegie"
            - run: git commit -a "circle ci commit"
            - run: git push
workflows:
  build-and-test-and-push:
    jobs:
      - build-and-test-and-push
